apiVersion: v1
kind: Secret
metadata:
  name: {{ include "car-dealership.fullname" . }}-backend-secret
type: Opaque
stringData:
{{- range $key, $val := .Values.backend.secretEnv }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
