apiVersion: v1
kind: Service
metadata:
  name: {{ include "car-dealership.fullname" . }}-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ include "car-dealership.fullname" . }}-backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 5000
