apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: car-dealership
type: Opaque
stringData:
  JWT_SECRET: "replace-me"
  MYSQL_HOST: "replace-me"
  MYSQL_USER: "replace-me"
  MYSQL_PASSWORD: "replace-me"
  MYSQL_DB: "replace-me"
  MONGO_URI: "replace-me"
